export const ADD_RULE = 'ADD_RULE'
export const DELETE_RULE = 'DELETE_RULE'
export const EDIT_RULE = 'EDIT_RULE'
export const ENABLE_RULE = 'ENABLE_RULE'
export const DISABLE_RULE = 'DISABLE_RULE'
export const CLEAR_RULES = 'CLEAR_RULES'
export const IMPORT_RULES = 'IMPORT_RULES'
export const APPEND_RULES = 'APPEND_RULES'
